# current fund - update this for new iteration
current_fund:
  iteration: "2025 - Summer Major"
  start_date: 2025-06-06 2:00
  sheet_id: "1IRZ7yPhBAYOZ3BHpdx3zPNdOhwPvBb3__poumHoieVk"
  sheet_gid: "408268708"
  checkpoints:
    3: "Hornet Excelsior"
    5: "Hammer Boxer"
    7: "Crisis"
    9: "Magnum Bombard"
    10: "Armadillo"
    11: "Legendary Key"
    12: "Hammer SP"
  notes: []

# past funds - move previous down to archive
archive:
  s22:
    start_date: 2022-07-04 2:00
    end_date: 2022-08-08 2:00
    sheet_id: "1IRZ7yPhBAYOZ3BHpdx3zPNdOhwPvBb3__poumHoieVk"
    sheet_gid: "1817523881"
    final_fund: 18516000
    checkpoints:
      1: "Nuclear Energy"
      4: "Prot Slot"
      7: "Skin Container"
      8: "Magnetic Pellets"
      9: "Helios"
      10: "Hammer LGC"
      11: "Vacuum Shell"
      12: "Swarm"
      13: "Pulsar"
      14: "Armadillo"
      15: "Crisis"
    notes: [["2022-07-04 02:00", "2022-07-04 17:33"], ["2022-07-14 18:30", "2022-07-16 03:30"]]
  w23:
    start_date: 2023-11-17 2:00
    end_date: 2023-12-20 2:00
    sheet_id: "1GiJQvvwp9cGWyRom5x6gc8qUjgUL2ONWyKfewBVY6sA"
    sheet_gid: 0
    final_fund: 16669500
    checkpoints:
      1: "Nuclear Energy"
      2: "Module Slot"
      10: "Gauss GT"
      11: "Nuclear Energy"
      20: "Freeze GT"
      21: "Nuclear Energy"
      30: "Hunter GT"
      31: "Nuclear Energy"
      32: "Module Slot"
      34: "Magnum Pulsar"
      36: "Gauss Pulsar"
      38: "Shaft Pulsar"
      40: "Skin Container"
      41: "Nuclear Energy"
      45: "100 Nuclear Energy"
      46: "100 Containers"
      47: "30 Weekly Containers"
      48: "90 Ultra Containers"
      50: "Skin Container"
    notes: [["2023-11-17 02:00", "2023-11-18 17:37"], ["2023-11-20 06:30", "2023-11-21 09:00"]]
  s24:
    start_date: 2024-06-07 2:00
    end_date: 2024-07-05 2:00
    sheet_id: "1IRZ7yPhBAYOZ3BHpdx3zPNdOhwPvBb3__poumHoieVk"
    sheet_gid: "1900607599"
    final_fund: 16681500
    checkpoints:
      1: "Nuclear Energy"
      2: "Module Slot"
      11: "Shaft Jamming Sight"
      12: "Nuclear Energy"
      13: "Crisis"
      15: "Magnum Freezing Core"
      17: "Armadillo"
      19: "Vulcan Freezing Band"
      21: "Twins GT"
      23: "Smoky Hyperspeed Rounds"
      25: "Legendary Key"
      27: "Mammoth GT"
      29: "Firebird Critical Mix"
      30: "3 Legendary Keys"
    notes: [["2024-06-13 16:30", "2024-06-14 06:3"], ["2024-06-28 01:30", "2024-07-01 22:00"], ["2024-07-02 23:30", "2024-07-03 14:30"]]
  w24:
    start_date: 2024-11-22 2:00
    end_date: 2024-12-21 2:00
    sheet_id: "1mGZVcTbSvR2KE648HvHHHW7Cyqn-qtjI6bEqTbkte-o"
    sheet_gid: "0"
    final_fund: 8296500
    checkpoints:
      1: "Nuclear Energy"
      2: "Grenades"
      11: "Striker Tandem"
      12: "Nuclear Energy"
      13: "Magnum Bombard"
      15: "Armadillo"
      17: "Isida Sustainable Nanobots"
      19: "Magnum Destroyer"
      21: "Ricochet GT"
      23: "Ricochet Pulsar"
      25: "Legendary Key"
      27: "Titan GT"
      29: "Gauss Nemesis"
      30: "3 Legendary Keys"
    notes: []
