[project]
name = "tanki-fund-tracker"
version = "3.1"
dependencies = [
    "beautifulsoup4",
    "bs4",
    "gspread",
    "matplotlib",
    "numpy",
    "pandas",
    "plotly",
    "requests",
    "scikit-learn",
    "streamlit",
    "PyYAML",
    "typing",
]
